### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by sergioventurini**
many little updates added and bugs fixed

### CODE REVIEW

**Comment by steppdev** [comment]
Sergio,   thanks for fixing all these small problems.Somehow, there are two files that have conflicts: The dontrun { }  seems to be missing for those two examples.However, I don't see the differences following the link that you provide. Can you take a look to see why ?

1. balance_example.Rd

<<<<<<< try_sergio
res_bal <- balance_patients(ranger1, ranger2, maxnsubpops, balance_example$covar,
  plot = TRUE, verbose = TRUE, contour = TRUE, nlevels = 6)
=======
\dontrun{res_bal <- balance_patients(ranger1, ranger2, maxnsubpops, balance_example$covar,
  plot = TRUE, verbose = TRUE, contour = TRUE, nlevels = 6, border = TRUE)}
  
>>>>>>> master
}

2. balance_patients.Rd

<<<<<<< try_sergio
res_bal <- balance_patients(ranger1, ranger2, maxnsubpops, balance_example$covar,
  plot = TRUE, verbose = TRUE, contour = TRUE, nlevels = 6)
=======
\dontrun{res_bal <- balance_patients(ranger1, ranger2, maxnsubpops, balance_example$covar,
  plot = TRUE, verbose = TRUE, contour = TRUE, nlevels = 6, border = TRUE)}
  
>>>>>>> master
}


Best,Wai-Ki

    On Thursday, February 25, 2021, 10:13:31 AM EST, Sergio Venturini <notifications@github.com> wrote:  
 
 
many little updates added and bugs fixed

You can view, comment on, or merge this pull request online at:

  https://github.com/steppdev/stepp/pull/9

Commit Summary
   
   - some updates

File Changes
   
   -  M DESCRIPTION (4) 
   -  M R/stepp.R (27) 
   -  M R/steppes.R (216) 
   -  M R/stmodel.R (4) 
   -  M R/stmodelCI.R (241) 
   -  M R/stmodelGLM.R (1041) 
   -  M R/stmodelKM.R (346) 
   -  M R/stsubpop.R (36) 
   -  M R/stutil.R (10) 
   -  M R/stwin.R (141) 
   -  M R/utility.R (129) 
   -  M data/aspirin.rda (0) 
   -  A data/simdataKM.rda (0) 
   -  M man/aspirin.Rd (2) 
   -  M man/balance_example.Rd (2) 
   -  M man/balance_patients.Rd (7) 
   -  M man/bigCI.Rd (2) 
   -  M man/bigKM.Rd (2) 
   -  M man/gen.tailwin.Rd (36) 
   -  A man/simdataKM.Rd (64) 
   -  M man/stepp.GLM.Rd (5) 
   -  M man/stepp.win.Rd (3) 
   -  M man/stmodelGLM-class.Rd (3) 
   -  M man/stwin-class.Rd (6) 
   -  M tests/tests.R (222) 

Patch Links:
   
   - https://github.com/steppdev/stepp/pull/9.patch
   - https://github.com/steppdev/stepp/pull/9.diff

**Comment by sergioventurini** [comment]
hi wai-ki,

i just pushed the new version of the .Rd files with the \dontrun{} but i’m not able to create a new pull request. maybe this is due to the fact that you did not merged the previous one.

please let me know.

thanks.


sergio

**Comment by steppdev** [comment]
Update merged into master.

**Review by steppdev — COMMENTED** [review]
Thanks for all the changes among the files.

**Pull request merged**
